import React from 'react';
import {
  LabelData,
  ModalContainerFullScreen,
} from '../../styledModalComponents';
import ModalHeaderComponent from '../../ModalHeaderComponent';
import { useSelector } from 'react-redux';
import { RootState } from '../../../../roomStore';
import styled from 'styled-components';
import { InfoIcon } from '../../../../assets/icons';
import { getExportMyData } from '../../../../networking/api-requests/user.api';
import {
  SharedSettingsCenterContainer,
  SharedSettingsColumnContainer,
  SharedSettingsInfoPanel,
  SharedSettingsInfoText,
  SharedSettingsLabelData,
  SharedSettingsSectionContainer,
  SharedSettingsStyledButton,
  SharedSettingsStyledLabel,
} from '../SharedStyledComponents';

interface ManageDataModalProps {
  handleCloseModal: any;
}

const InfoPanel = styled.div`
  background-color: '#F3F6FC';
  display: flex;
  gap: 8px;
  border-radius: 8px;
  padding: 8px;
`;

const ManageDataModal: React.FC<ManageDataModalProps> = ({
  handleCloseModal,
}) => {
  const { config } = useSelector((state: RootState) => state.chatSettingStore);

  const handleDownloadClick = async () => {
    const exportedData = await getExportMyData();
    const binaryData = exportedData.data;
    console.log(binaryData);
    const blob = new Blob([binaryData], { type: 'text/plain' });

    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = 'mydata.json';

    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);

    URL.revokeObjectURL(url);
  };

  return (
    <ModalContainerFullScreen>
      <ModalHeaderComponent
        handleCloseModal={handleCloseModal}
        headerTitle={'Manage Data'}
      />
      <SharedSettingsCenterContainer>
        <SharedSettingsColumnContainer>
          <SharedSettingsSectionContainer>
            <SharedSettingsStyledLabel>
              Download your data
            </SharedSettingsStyledLabel>
            <LabelData
              style={{
                fontSize: '12px',
                textAlign: 'start',
              }}
            >
              You own your data. Tap the button below to download a copy of your
              data
            </LabelData>
          </SharedSettingsSectionContainer>
          <SharedSettingsStyledButton
            borderColor={config.colors.primary || '#0052CD'}
            onClick={handleDownloadClick}
          >
            Download your data
          </SharedSettingsStyledButton>
        </SharedSettingsColumnContainer>
        <SharedSettingsColumnContainer>
          <SharedSettingsSectionContainer>
            <SharedSettingsStyledLabel>
              Download your data
            </SharedSettingsStyledLabel>
            <SharedSettingsLabelData>
              Use this only if you want to permanently delete your account &
              data from our system.
            </SharedSettingsLabelData>
          </SharedSettingsSectionContainer>
          <SharedSettingsInfoPanel
            bgColor={config?.colors?.secondary || '#F3F6FC'}
          >
            <div>
              <InfoIcon color={config?.colors?.primary} />
            </div>
            <SharedSettingsInfoText>
              Due to the immutable nature of distributed ledger technology,
              network nodes operated by the community may still retain
              historical transactions generated by your account, however your
              personally identifiable information such as your name, e-mail,
              your key-value storage etc will be removed. Any of your digital
              assets will be lost.
            </SharedSettingsInfoText>
          </SharedSettingsInfoPanel>
          <SharedSettingsStyledButton borderColor="#E53935">
            Delete My Account
          </SharedSettingsStyledButton>
        </SharedSettingsColumnContainer>
      </SharedSettingsCenterContainer>
    </ModalContainerFullScreen>
  );
};

export default ManageDataModal;
